name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: elementary/docker:unstable
      
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y meson gobject-introspection libgtk-3-dev libgee-0.8-dev libgstreamer-plugins-base1.0-dev libunity-dev valac
    - name: Build
      run: |
        meson build --prefix=/usr
        cd build
        ninja install
